import { describe, expect, it } from 'vitest';
import { Simulation } from '../src/game/systems/Simulation';
import { grantMoonRewards } from '../src/game/systems/MoonRewards';
import { migrateProfile, newProfile } from '../src/game/persistence/Profile';
import { enemies, objectiveComplete, validateMoon } from '../src/game/content/shatteredMoon';
import type { Actions } from '../src/game/systems/types';
const idle: Actions = {move:{x:0,y:0},aim:{x:1,y:0},cast:false,impulse:false,pulse:false,surge:false};
const create = (room = 0) => {const s=new Simulation('pve',100,147,{dungeonId:'shattered-moon'});if(room)s.enterRoom(room);for(let i=0;i<73;i++)s.step(idle);return s;};
describe('Shattered Moon mechanics',()=>{
  it('validates content and runs 20 active Mites deterministically at fixed ticks',()=>{
    validateMoon();const a=create(),b=create();expect(a.actors.length).toBe(21);const start=performance.now();for(let i=0;i<600;i++){a.step(idle);b.step(idle);}const ms=performance.now()-start;
    expect(a.actors.map(e=>[e.x,e.y,e.integrity.current])).toEqual(b.actors.map(e=>[e.x,e.y,e.integrity.current]));expect(a.actors.every(e=>Number.isFinite(e.x+e.y+e.vx+e.vy))).toBe(true);expect(a.moon!.states.size).toBe(20);expect([...a.moon!.states.values()].filter(s=>s.state==='attached').length).toBeLessThanOrEqual(3);console.log(`20-Mite simulation: ${(ms/1200).toFixed(3)} ms/tick, ${ms.toFixed(1)} ms / 1200 ticks`);
  });
  it('keeps Integrity across rooms, refills Flux, and ignores combat on safe arrival',()=>{const s=create();s.player.integrity.current=43;s.player.channel.flux=4;s.enterRoom(1);const x=s.player.x;s.step({...idle,cast:true,surge:true,move:{x:1,y:0}});expect(s.player.integrity.current).toBe(43);expect(s.player.channel.flux).toBe(100);expect(s.player.x).toBe(x);expect(s.player.melee.phase).toBe('idle');});
  it('caps attachment, removes attached Mites with compressed melee, and launches orbiting Mites',()=>{const sim=create(),m=sim.moon!,a=sim.actors[1],s=m.states.get(a.id)!;s.state='attached';sim.player.mass.distribution=1;sim.player.melee.phase='active';sim.player.melee.hits=[];sim.player.hitPause=0;m.update(1/60);expect(a.alive).toBe(false);const b=sim.actors[2],t=m.states.get(b.id)!;t.state='orbit';sim.player.channel.mode='pulse';m.force(b,{x:600,y:0},1/60);expect(t.state).toBe('recovery');expect(t.launched).toBeGreaterThan(0);expect(b.vx).toBeGreaterThan(100);});
  it('keeps the Crab anchored until both independent anchors break; force then exposes its underside',()=>{const sim=create(2),m=sim.moon!,a=sim.actors[1],s=m.states.get(a.id)!;a.vx=0;sim.player.channel.mode='pull';m.force(a,{x:600,y:0},1);expect(a.vx).toBe(0);const anchors=s.parts.filter(p=>p.id.includes('anchor'));m.hitPart(a,anchors[0],100,true);expect(s.massClass).toBe('Anchored');m.hitPart(a,anchors[1],100,false);expect(s.massClass).toBe('Heavy');for(let i=0;i<180;i++)m.force(a,{x:600,y:0},1/60);expect(s.state).toBe('stagger');const hp=a.integrity.current;m.hit(a,20,true);expect(hp-a.integrity.current).toBe(40);expect(m.brokenParts).toBe(2);});
  it('requires Pull to remove a loosened plate',()=>{const sim=create(2),m=sim.moon!,a=sim.actors[1],s=m.states.get(a.id)!,plate=s.parts[2];m.hitPart(a,plate,100,false);expect(plate.loosened).toBe(true);expect(plate.broken).toBe(false);sim.player.channel.mode='pulse';m.force(a,{x:600,y:0},1);expect(plate.broken).toBe(false);sim.player.channel.mode='pull';m.force(a,{x:600,y:0},1/60);expect(plate.broken).toBe(true);});
  it('materializes Wisps only through sustained Pull and restores Flux on defeat',()=>{const sim=create(3),m=sim.moon!,a=sim.actors[1],s=m.states.get(a.id)!;expect(m.hit(a,100,true)).toBe(0);sim.player.channel.mode='pulse';m.force(a,{x:600,y:0},2);expect(s.materialized).toBe(0);sim.player.channel.mode='pull';for(let i=0;i<110;i++)m.force(a,{x:600,y:0},1/60);expect(s.materialized).toBeGreaterThan(0);expect(m.revealed).toBe(1);sim.player.channel.flux=10;m.hit(a,200,true);m.tickEnemy(a,0);expect(sim.player.channel.flux).toBe(40);});
  it('attributes three environmental executions and deterministic drops',()=>{const runs=[create(),create()];for(const sim of runs){const m=sim.moon!;m.environmentHit(sim.actors[1],100,'Wall impact');m.environmentHit(sim.actors[2],100,'Enemy collision');m.environmentHit(sim.actors[3],100,'Launched debris');m.update(1/60);expect(m.physics).toBe(3);expect(m.events.filter(e=>e.text.startsWith('Physics Execution')).length).toBe(3);}expect(runs[0].moon!.materials).toEqual(runs[1].moon!.materials);});
  it('implements both modifiers without removing base counterplay',()=>{const sim=create(2),m=sim.moon!,a=sim.actors[2],s=m.states.get(a.id)!;expect(s.elite).toBe('Dense');sim.player.channel.mode='pulse';const before=a.vx;m.force(a,{x:600,y:0},1);expect(a.vx-before).toBe(375);const other=create(3),u=other.moon!,mite=other.actors.find(a=>a.kind==='meteor-mite')!;u.hit(mite,100,true);u.tickEnemy(mite,0);expect(u.explosions).toHaveLength(1);expect(u.explosions[0].timer).toBeGreaterThan(1);});
  it('requires armor objects, organ stabilization, overload and a deliberate boss Collapse',()=>{const sim=create(4),m=sim.moon!,a=m.boss!,s=m.states.get(a.id)!;sim.player.channel.mode='pull';m.force(a,{x:600,y:0},1);expect(a.vx).toBe(0);expect(m.hit(a,9999,true)).toBe(0);for(const p of s.parts.filter(p=>p.id.includes('armor'))){m.hitPart(a,p,1000,false);expect(p.broken).toBe(false);m.hitPart(a,p,1000,true);}expect(s.phase).toBe(1);for(const p of s.parts.filter(p=>p.id.includes('organ'))){m.hitPart(a,p,1000,false);expect(p.broken).toBe(false);p.exposed=8;m.hitPart(a,p,1000,false);}expect(s.phase).toBe(2);expect(m.hit(a,9999,true)).toBe(0);s.exposure=10;m.hit(a,9999,true);expect(s.state).toBe('collapse');expect(a.alive).toBe(true);m.tickEnemy(a,2.6);expect(a.alive).toBe(false);});
  it('replenishes exhausted boss objects and never gives the Titan global Displacement',()=>{const sim=create(4),m=sim.moon!,s=m.states.get(m.boss!.id)!;m.objects=[];m.objectTimer=0;m.updateObjects(1/60);expect(m.objects.length).toBe(1);m.objects[0].ttl=0;m.updateObjects(1/60);expect(m.objects.length).toBe(0);m.objectTimer=0;m.updateObjects(1/60);expect(m.objects.length).toBe(1);m.force(m.boss!,{x:800,y:0},60);expect(s.displacement).toBe(0);});
  it('supports every encounter objective',()=>{const p={enemies:0,destroyed:2,revealed:3,elapsed:60,physics:3,protectedHP:50,choice:true,bossDefeated:true};for(const type of ['elimination','demolition','hunt','survival','physics-puzzle','protection','elite','reward','boss'] as const)expect(objectiveComplete({type},p)).toBe(true);expect(objectiveComplete({type:'protection'},{...p,protectedHP:0})).toBe(false);});
  it('settles first-clear exactly once, persists materials in v3, and rejects failed run rewards',()=>{const profile=newProfile();const run=()=>{const sim=create(4);sim.moon!.state='exit';sim.finish(true,'test');return sim.moon!;};const a=run();expect(grantMoonRewards(profile,a)?.firstClear).toBe(true);expect(grantMoonRewards(profile,a)).toBeNull();expect(grantMoonRewards(profile,run())?.firstClear).toBe(false);expect(profile.materials['Evolution Core']).toBe(1);expect(migrateProfile(JSON.parse(JSON.stringify(profile))).materials).toEqual(profile.materials);const failed=create();failed.finish(false,'collapse');expect(grantMoonRewards(profile,failed.moon!)).toBeNull();expect(failed.moon!.state).toBe('failure');expect(migrateProfile({schemaVersion:2,maximumMass:150,upgradeMaterial:9}).upgradeMaterial).toBe(9);});
  it('offers a single optional recovery or materials choice',()=>{const sim=create(3),m=sim.moon!;sim.player.integrity.current=40;expect(m.chooseCache('recovery')).toBe(false);sim.roomCleared=true;expect(m.chooseCache('recovery')).toBe(true);expect(sim.player.integrity.current).toBe(75);expect(m.chooseCache('materials')).toBe(false);expect(enemies['lunar-devourer'].taxonomy).toBe('Titans');});
});
