import { shatteredMoon, materialIds } from '../content/shatteredMoon';
import Phaser from 'phaser';
import { backdrop, store, ui } from './Scenes';
import { dungeon } from '../content/dungeon';
import { manifestations, manifestationFor } from '../content/manifestations';
import { economy } from '../config/economy';
import { equipManifestation, summon, upgradeManifestation } from '../systems/EconomySystem';

export class DungeonSelectScene extends Phaser.Scene {
  constructor() { super('DungeonSelectScene'); }
  create(): void {
    backdrop(this); const profile = store.load();
    ui().innerHTML = `<main class="meta-screen"><header><span class="brand">◈ COSMIC CORE</span><button id="back" class="quiet">← Main menu</button></header><section class="meta-heading"><div class="eyebrow">DUNGEONS / 01</div><h1>The Silent Orbit</h1><p>Enter the vessel. Learn its weight. Break the anchored Core.</p></section><div class="dungeon-map">${dungeon.rooms.map((room, i) => `<article class="dungeon-node"><span class="node-index">0${i + 1}</span><small>${i === 2 ? 'BOSS CHAMBER' : 'COMBAT ROOM'}</small><h2>${room.name}</h2><p>${room.instruction}</p><span class="node-symbol">${['⌁', '◎', '◈'][i]}</span></article>`).join('<span class="node-link">→</span>')}</div><section class="dungeon-bottom"><div><div class="difficulty">${dungeon.difficulties.map(d => `<button class="quiet ${d.playable ? 'selected' : ''}" ${d.playable ? '' : 'disabled'}>${d.name}${d.playable ? '' : ' · Locked'}</button>`).join('')}</div><p>${economy.energyEnabled ? `Energy ${profile.energy}/${economy.energyMax} · Entry ${dungeon.energyCost}` : 'Energy disabled for testing · Manual runs only'}<br>First clear: ${profile.firstClears.includes(`${dungeon.id}:normal`) ? 'Claimed' : `+${dungeon.rewards.firstClear.mass} mass · +${dungeon.rewards.firstClear.materials} material · +${dungeon.rewards.firstClear.currency} test currency`}</p></div><div class="dungeon-start"><small>VESSEL / ${manifestationFor(profile.equippedManifestation).name.toUpperCase()}</small><button id="enter-dungeon" class="primary-button" ${economy.energyEnabled && profile.energy < dungeon.energyCost ? 'disabled' : ''}>Enter dungeon ↗</button><small>Auto-repeat unavailable · No time gate</small></div></section></main>`;
    ui().querySelector('.dungeon-map')!.insertAdjacentHTML('afterend','<section class="moon-selection"><h2>The Shattered Moon</h2><p>Cosmic fauna, breakable anchors and a three-phase Titan. Solo · Normal · 7–10 minutes.</p><div class="moon-route">'+shatteredMoon.rooms.map((r,i)=>'<span>'+String(i+1).padStart(2,'0')+' / '+r.name+'</span>').join('')+'</div><p>First clear: '+(profile.firstClears.includes('shattered-moon:normal')?'Evolution Core claimed':'Evolution Core ×1 guaranteed')+'</p><small>'+materialIds.map(id=>id+': '+profile.materials[id]).join(' · ')+'</small><div id="moon-entry"></div></section>');
    const moon = document.createElement('button'); moon.id = 'enter-moon'; moon.className = 'primary-button'; moon.textContent = 'The Shattered Moon · 5 rooms · Enter ↗'; moon.onclick = () => { this.registry.set('dungeonId', 'shattered-moon'); this.scene.start('PvEMissionScene'); }; ui().querySelector('#moon-entry')!.append(moon);
    ui().querySelector<HTMLButtonElement>('#back')!.onclick = () => this.scene.start('MainMenuScene');
    ui().querySelector<HTMLButtonElement>('#enter-dungeon')!.onclick = () => { this.registry.set('dungeonId', 'silent-orbit'); this.scene.start('PvEMissionScene'); };
  }
}
export class CollectionScene extends Phaser.Scene {
  message = '';
  constructor() { super('CollectionScene'); }
  create(): void { backdrop(this); this.message = ''; this.draw(); }
  draw(): void {
    const p = store.load();
    ui().innerHTML = `<main class="meta-screen collection-screen"><header><span class="brand">◈ COSMIC CORE</span><span class="wallet">TEST CURRENCY ${p.summonCurrency} · MATERIAL ${p.upgradeMaterial} · SHARDS ${p.resonanceShards}</span><button id="back" class="quiet">← Main menu</button></header><section class="meta-heading"><div class="eyebrow">MANIFESTATIONS / YOUR CORE, EXPRESSED</div><h1>One Core. New possibilities.</h1><p>Three prototype expressions. Shared mass rules. No paid currency.</p></section><div class="manifestations">${manifestations.map(m => { const owned = p.ownedManifestations.includes(m.id), level = p.manifestationLevels[m.id] ?? 1; return `<article class="manifestation ${p.equippedManifestation === m.id ? 'equipped' : ''}" style="--accent:#${m.color.toString(16)}"><div class="manifestation-top"><small>${m.rarity.toUpperCase()} / ${m.affinity.toUpperCase()}</small><span>${owned ? `LV ${level}` : 'UNOWNED'}</span></div><div class="vessel-preview" aria-label="Neutral humanoid vessel"></div><h2>${m.name}</h2><p>${m.description}</p><ul>${m.abilities.map(a => `<li>${a}</li>`).join('')}<li>${m.passive}</li></ul><small>Duplicates → ${m.duplicateShards} Resonance Shards</small><div class="manifestation-actions"><button class="quiet" data-equip="${m.id}" ${!owned || p.equippedManifestation === m.id ? 'disabled' : ''}>${p.equippedManifestation === m.id ? 'Equipped' : owned ? 'Equip' : 'Summon to equip'}</button><button class="quiet" data-upgrade="${m.id}" ${!owned || level >= m.upgrade.maxLevel || p.upgradeMaterial < m.upgrade.materialCost * level ? 'disabled' : ''}>${level >= m.upgrade.maxLevel ? 'Max level' : `Upgrade · ${m.upgrade.materialCost * level} material`}</button></div></article>`; }).join('')}</div><section class="summon-panel"><div><strong>Free developer summon</strong><p>Uses earned test currency. An unowned expression is guaranteed within ${economy.pityAt} summons while any remain.<br>Progress toward guarantee: ${p.pity}/${economy.pityAt} · Prototype seed ${economy.seed}. Rates are test fixtures.</p><div id="summon-result" role="status">${this.message || 'Complete a dungeon to earn test currency. Duplicates are never required.'}</div></div><button id="summon" class="primary-button" ${p.summonCurrency < economy.summonCost ? 'disabled' : ''}>Summon · ${economy.summonCost} test currency ✦</button></section><small>Upgrades use materials, never Maximum Mass. PvP suppresses upgrades and caps property modifiers within each mass division.</small></main>`;
    ui().querySelector<HTMLButtonElement>('#back')!.onclick = () => this.scene.start('MainMenuScene');
    ui().querySelectorAll<HTMLButtonElement>('[data-equip]').forEach(b => b.onclick = () => { const profile = store.load(); if (equipManifestation(profile, b.dataset.equip!)) this.message = store.save(profile) ? `${manifestationFor(b.dataset.equip!).name} equipped.` : 'Storage unavailable. Equip was not saved.'; this.draw(); });
    ui().querySelectorAll<HTMLButtonElement>('[data-upgrade]').forEach(b => b.onclick = () => { const profile = store.load(); if (upgradeManifestation(profile, b.dataset.upgrade!)) this.message = store.save(profile) ? 'Upgrade saved. Maximum Mass is unchanged.' : 'Storage unavailable. Upgrade was not saved.'; this.draw(); });
    ui().querySelector<HTMLButtonElement>('#summon')!.onclick = () => { const profile = store.load(), result = summon(profile); if (result) this.message = store.save(profile) ? `${manifestationFor(result.id).name} · ${result.duplicate ? `Duplicate converted to ${result.shards} Resonance Shards` : 'New Manifestation unlocked'}${result.pity ? ' · Guarantee reached' : ''}` : 'Storage unavailable. Summon was not saved or charged.'; this.draw(); };
  }
}
